language: c
compiler:
  - clang
  - gcc
install:
  - curl --silent --location https://raw.github.com/clear-code/cutter/master/data/travis/setup.sh | sh
  - ./configure
script: make all && test/run_tests.sh
